# .travis.yml -- Travis CI specification file.
# Copyright 2016-2018 the Tectonic Project
# Licensed under the MIT License.

language: rust

cache: cargo

matrix:
  include:
    - os: linux
      sudo: required
      dist: xenial
      rust: stable
      env: RUSTFLAGS="-C link-dead-code"
    - os: linux
      sudo: required
      dist: xenial
      rust: beta
    - os: linux
      sudo: required
      dist: xenial
      rust: nightly
    - os: osx
      osx_image: xcode8.3
      rust: stable
  allow_failures:
    - rust: nightly

addons:
  apt:
    packages:
      - libgraphite2-dev
      - libharfbuzz-dev
      - libfontconfig1-dev
      - libicu-dev
      - libssl-dev
      - openssl
      - zlib1g-dev

# At the moment, Travis' Xenial images have an auto-update daemon that can
# lock the apt/dpkg system under us. See
# https://github.com/travis-ci/travis-cookbooks/issues/952 and
# https://unix.stackexchange.com/questions/315502/how-to-disable-apt-daily-service-on-ubuntu-cloud-vm-image
# . We adopt the workaround from the StackExchange post.

before_install:
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew update
    else
      sudo systemctl stop apt-daily.service &&
      sudo systemctl kill --kill-who=all apt-daily.service &&
      while ! (systemctl list-units --all apt-daily.service | fgrep -q dead) ; do
        sleep 1
      done &&
      sudo add-apt-repository -y ppa:k-peter/tectonic-ci &&
      sudo apt-get update
    fi

install:
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew install graphite2 &&
      brew install harfbuzz --with-graphite2 &&
      brew install --force openssl
    else
      sudo apt-get install -y libharfbuzz-dev
    fi

before_script:
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      export OPENSSL_INCLUDE_DIR=$(brew --prefix openssl)/include &&
      export OPENSSL_LIB_DIR=$(brew --prefix openssl)/lib &&
      export DEP_OPENSSL_INCLUDE=$(brew --prefix openssl)/include &&
      export PKG_CONFIG_PATH=/usr/local/opt/icu4c/lib/pkgconfig
    fi

script:
  - |
    cargo build --verbose &&
    cargo test

after_success: |
  if [[ "$TRAVIS_OS_NAME" == "linux" && "$TRAVIS_RUST_VERSION" == "stable" ]]; then
    sudo apt-get install -y kcov &&
    cargo install cargo-kcov &&
    cargo test --no-run &&
    env RUNNING_COVERAGE=1 cargo kcov --no-clean-rebuild &&
    bash <(curl -s https://codecov.io/bash)
  fi

before_deploy:
  - openssl aes-256-cbc -K $encrypted_bc40b17e21fa_key -iv $encrypted_bc40b17e21fa_iv
    -in dist/deploy_key.enc -out /tmp/deploy_key -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_key
  - ssh-add /tmp/deploy_key

deploy:
  provider: script
  script: dist/arch/deploy.sh
  on:
    tags: true
