language: rust

os: osx
osx_image: xcode8.2

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly

before_install:
  - brew update
  - brew install graphite2
  - brew install harfbuzz --with-graphite2
  - brew install poppler

script:
  - PKG_CONFIG_PATH=/usr/local/opt/icu4c/lib/pkgconfig cargo build --verbose
  - ./tests/run.sh
