# .travis.yml -- Travis CI specification file.
# Copyright 2016-2017 the Tectonic Project
# Licensed under the MIT License.

language: rust

cache: cargo
sudo: false

matrix:
  include:
    - os: linux
      dist: trusty
      rust: stable
    - os: linux
      dist: trusty
      rust: beta
    - os: linux
      dist: trusty
      rust: nightly
    - os: osx
      osx_image: xcode8.2
      rust: stable
  allow_failures:
    - rust: nightly

addons:
  apt:
    packages:
      - libgraphite2-dev
      - libharfbuzz-dev
      - libfontconfig1-dev
      - libicu-dev
      - zlib1g-dev
      - openssl

before_install:
  - '[[ "$TRAVIS_OS_NAME" != "osx" ]] || brew update'

install:
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew install graphite2 &&
      brew install harfbuzz --with-graphite2 &&
      brew install --force openssl
    fi

before_script:
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      export OPENSSL_INCLUDE_DIR=$(brew --prefix openssl)/include &&
      export OPENSSL_LIB_DIR=$(brew --prefix openssl)/lib &&
      export DEP_OPENSSL_INCLUDE=$(brew --prefix openssl)/include &&
      export PKG_CONFIG_PATH=/usr/local/opt/icu4c/lib/pkgconfig
    fi

script:
  - |
    cargo build --verbose &&
    cargo test

before_deploy:
  - openssl aes-256-cbc -K $encrypted_bc40b17e21fa_key -iv $encrypted_bc40b17e21fa_iv
    -in dist/deploy_key.enc -out /tmp/deploy_key -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_key
  - ssh-add /tmp/deploy_key

deploy:
  provider: script
  script: dist/arch/deploy.sh
  on:
    tags: true
