# .travis.yml -- Travis CI specification file.
# Copyright 2016-2017 the Tectonic Project
# Licensed under the MIT License.

language: rust
sudo: false

cache: cargo

os: osx
osx_image: xcode8.2

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly

before_install:
  - brew update

install:
  - brew install graphite2
  - brew install harfbuzz --with-graphite2
  - brew install openssl poppler
  - pip install 'travis-cargo<0.2' --user

before_script:
  - |
    export PATH=$HOME/.local/bin:$PATH &&
    export OPENSSL_INCLUDE_DIR=$(brew --prefix openssl)/include &&
    export OPENSSL_LIB_DIR=$(brew --prefix openssl)/lib &&
    export DEP_OPENSSL_INCLUDE=$(brew --prefix openssl)/include &&
    export PKG_CONFIG_PATH=/usr/local/opt/icu4c/lib/pkgconfig

# Temporary(?) hack: `cargo test` on OSX fails since it runs the test programs
# with DYLD_LIBRARY_PATH set (see cargo:
# src/cargo/ops/cargo_rustc/compilation.rs:fill_env()), which in our case
# interacts poorly with the fact that one of the system frameworks uses an
# internal version of libpng that clashes with the one provided by Homebrew
# (see, e.g.,
# http://stackoverflow.com/questions/17643509/conflict-between-dynamic-linking-priority-in-osx).
# But the test programs work if we just run them manually. So, do that. This
# is not awesome since it won't scale well at all as we add more test runner
# programs.

script:
  - |
    travis-cargo build --verbose &&
    travis-cargo test --no-run &&
    target/debug/tex_outputs-???????????????? && target/debug/trip-????????????????
