[target.arm-unknown-linux-musleabihf]
image = "tectonictypesetting/crossbuild:arm-unknown-linux-musleabihf"

[target.x86_64-unknown-linux-musl]
image = "tectonictypesetting/crossbuild:x86_64-unknown-linux-musl"
