# Copyright 2018-2019 the Tectonic Project
# Licensed under the MIT License

# This CI workflow builds and tests Tectonic on a synthetic PowerPC CPU to
# verify that we work on big-endian systems. It's not included in the Travis
# suite because the workflow is so different from our standard one, and Circle
# has a longer build time limit, which is important in this laughably
# inefficient approach that we're taking.
#
# Here we leverage the continuous deployment framework that's driven by our
# Travis CI configuration. When commits are merged to master, a tag called
# `continuous` is deleted and recreated to point to the latest version. This
# allows us to write tag-driven CD logic that closely parallels the release
# deployment logic that fires when a tag named `vX.Y.Z` is pushed to GitHub.
# Since Travis CI takes care of the tag creation, we actually ignore pushes to
# master, and instead just watch for events on the `continuous` tag.

version: 2

jobs:
  build:
    machine:
      image: circleci/classic:201711-01
    steps:
      # Print a notice aimed at confused pull-requesters:
      - run: echo "Testing Tectonic on a synthetic big-endian CPU; this will take a while."
      - run: echo "Sometimes the build stalls and times out; this is likely not your fault."
      - checkout
      - run:
          command: sudo bash .circleci/outer-build.sh $CIRCLE_WORKING_DIRECTORY
          no_output_timeout: 1800

  deploy:
    machine:
      image: circleci/classic:201711-01
    steps:
      - run: .circleci/deploy.sh

workflows:
  version: 2
  pull-request:
    jobs:
      - build:
          filters:
            branches:
              ignore: master
  continuous-deployment-build:
    jobs:
      - build:
          filters:
            tags:
              only: continuous
            branches:
              ignore: /.*/
      - deploy:
          requires:
            - build
  release-build:
    jobs:
      - build:
          filters:
            tags:
              only: /^v[0-9]\..*/
            branches:
              ignore: /.*/
      - deploy:
          requires:
            - build
