# Copyright 2019 the Tectonic Project
# Licensed under the MIT License.

jobs:

- job: rust_cross_build_${{ parameters.target_uscore }}
  pool:
    vmImage: 'ubuntu-18.04'

  steps:
    - script: |
        curl https://sh.rustup.rs -sSf | sh -s -- -y
        echo "##vso[task.setvariable variable=PATH;]$PATH:$HOME/.cargo/bin"
      displayName: Install rust
    - script: docker run --rm --privileged multiarch/qemu-user-static:register --reset --credential yes
      displayName: Set up QEMU execution of executable from test suite
    - script: docker run --rm -v $(pwd):/work:rw,Z tectonictypesetting/ttcross:latest
      displayName: Install custom-built cross tool
    - script: |
        ./cross test --target ${{ parameters.target }} --release --all
      displayName: Build and test
