# Test using TECTONIC_DEP_BACKEND=vcpkg
name: vcpkg

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-16.04, macos-latest, ubuntu-latest]
        include:
          - os: windows-latest
            rustflags: "-Ctarget-feature=+crt-static"
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - name: Install cargo-vcpkg
        run: cargo install cargo-vcpkg
      - name: Install dependencies
        run: cargo vcpkg build
      - name: Build Tectonic
        shell: bash
        env:
          TECTONIC_DEP_BACKEND: vcpkg
        run: |
          set -ex
          rustc --version
          cargo --version
          RUSTFLAGS=${{ matrix.rustflags }} cargo build
